"""Pure Campaign Core domain rules."""

from dm_assistant_core.domain.approval import (
    ApprovalScope,
    StaleApprovalError,
    create_approval_scope,
    validate_current_approval,
)
from dm_assistant_core.domain.authority import (
    AuthorityDecision,
    ConflictOutcome,
    resolve_observed_conflict,
)
from dm_assistant_core.domain.candidate_revision import resolve_explicit_candidate_revision
from dm_assistant_core.domain.change_sets import (
    ApplyChangeSetCommand,
    ChangeSetReceipt,
    ChangeSetRejectedError,
)
from dm_assistant_core.domain.chronology import (
    CALENDAR,
    CURRENT_CAMPAIGN_YEAR,
    GREGORIAN_CE,
    CalendarSpec,
    CalendarSpecError,
    CampaignDate,
    DateRole,
    compare_same_calendar,
    gregorian_ce_spec,
    resolve_relative_year,
)
from dm_assistant_core.domain.creative import create_bounded_read_aloud
from dm_assistant_core.domain.extraction import (
    EXTRACTION_SYSTEM_PROMPT,
    DocumentContext,
    ExtractedAssertion,
    ExtractionAuthority,
    ExtractionContract,
    ExtractionError,
    ExtractionHarness,
    ExtractionResult,
    GroundingError,
    SubjectResolution,
)
from dm_assistant_core.domain.models import ClaimState, PlanningClaim, Visibility
from dm_assistant_core.domain.pc_agency import represent_pc_campaign_direction
from dm_assistant_core.domain.plans import (
    PLAN_KIND_GUIDANCE,
    PlanKind,
    PlanKindGuidance,
    PlanKnowledgeBoundary,
    PlanLifecycle,
    knowledge_boundary_for,
)
from dm_assistant_core.domain.retrieval import (
    AnswerMode,
    EvidenceRole,
    RequesterRole,
    RequesterVisibility,
    RetrievalAuthority,
    RetrievalPolicy,
    RetrievalQuery,
    RetrievalReason,
    RetrievalRecord,
    RetrievalRecordKind,
    RetrievalResult,
    RetrievedEvidence,
)
from dm_assistant_core.domain.rules_elements import (
    MARKDOWN_CARD_PROFILE,
    MARKDOWN_CARD_PROFILE_VERSION,
    FeatMechanics,
    RulesElementMechanics,
    RulesKind,
    RulesMechanicsError,
    SpellMechanics,
    render_markdown_card,
)
from dm_assistant_core.domain.taxonomy import (
    ENTITY_KIND_GUIDANCE,
    INITIAL_TAGS,
    EntityKind,
    EntityKindGuidance,
    normalize_tag,
    normalize_tags,
)
from dm_assistant_core.domain.workflows import DirectLoreDecision, scope_direct_lore_update

__all__ = [
    "CALENDAR",
    "CURRENT_CAMPAIGN_YEAR",
    "ENTITY_KIND_GUIDANCE",
    "EXTRACTION_SYSTEM_PROMPT",
    "GREGORIAN_CE",
    "INITIAL_TAGS",
    "MARKDOWN_CARD_PROFILE",
    "MARKDOWN_CARD_PROFILE_VERSION",
    "PLAN_KIND_GUIDANCE",
    "AnswerMode",
    "ApplyChangeSetCommand",
    "ApprovalScope",
    "AuthorityDecision",
    "CalendarSpec",
    "CalendarSpecError",
    "CampaignDate",
    "ChangeSetReceipt",
    "ChangeSetRejectedError",
    "ClaimState",
    "ConflictOutcome",
    "DateRole",
    "DirectLoreDecision",
    "DocumentContext",
    "EntityKind",
    "EntityKindGuidance",
    "EvidenceRole",
    "ExtractedAssertion",
    "ExtractionAuthority",
    "ExtractionContract",
    "ExtractionError",
    "ExtractionHarness",
    "ExtractionResult",
    "FeatMechanics",
    "GroundingError",
    "PlanKind",
    "PlanKindGuidance",
    "PlanKnowledgeBoundary",
    "PlanLifecycle",
    "PlanningClaim",
    "RequesterRole",
    "RequesterVisibility",
    "RetrievalAuthority",
    "RetrievalPolicy",
    "RetrievalQuery",
    "RetrievalReason",
    "RetrievalRecord",
    "RetrievalRecordKind",
    "RetrievalResult",
    "RetrievedEvidence",
    "RulesElementMechanics",
    "RulesKind",
    "RulesMechanicsError",
    "SpellMechanics",
    "StaleApprovalError",
    "SubjectResolution",
    "Visibility",
    "compare_same_calendar",
    "create_approval_scope",
    "create_bounded_read_aloud",
    "gregorian_ce_spec",
    "knowledge_boundary_for",
    "normalize_tag",
    "normalize_tags",
    "render_markdown_card",
    "represent_pc_campaign_direction",
    "resolve_explicit_candidate_revision",
    "resolve_observed_conflict",
    "resolve_relative_year",
    "scope_direct_lore_update",
    "validate_current_approval",
]
